[tool.poetry]
name = "eargait"
version = "2.2.0"
description = "*Eargait* provides a set of algorithms and functions to process IMU data recorded with ear-worn IMU sensors and to estimate characteristic gait parameters. "
authors = ["Ann-Kristin Seifer <ann-kristin.seifer@fau.de>",
            "Arne Küderle <arne.kuederle@fau.de>"]
readme = "README.md"
homepage = "https://github.com/mad-lab-fau/eargait"
repository = "https://github.com/mad-lab-fau/eargait"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
joblib = ">=1.2.0"
tpcp = ">=0.12, <1.0.0"
scipy = "^1, !=1.6.0"
scikit-learn = "1.2.0"
pyts = "^0.11.0"
nilspodlib = "^3.2.2"
fau-colors = "^1.0.1"
signialib = "^2.6.0"
pandas = ">=1.5.2"
tensorflow = "^2.10.0"
numba =  [
    {version = ">=0.55"},
    {version = ">=0.55.2", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'"}
]
numpy = ">=1.20"
debugpy = "1.6.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.8.1"
prospector = "^1.7.7"
black = "^22.3.0"
isort = "^5.10.1"
poethepoet = "^0.10.0"
pyright = "^1.1.230"
numpydoc = "^1.4.0"
sphinx-gallery = "^0.11.0"
pydata-sphinx-theme = "^0.9.0"
recommonmark = "^0.7.1"
memory-profiler = "^0.58.0"
matplotlib = "^3.4.3"
toml = "^0.10.2"
Sphinx = "^5.1.1"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
    | \.virtual_documents
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
skip_gitignore = true

[tool.poe.tasks]
_format_black = "black ."
_format_isort = "isort ."
format = ["_format_black", "_format_isort"]
lint = { cmd = "prospector", help = "Lint all files with Prospector." }
_check_black = "black . --check"
_check_isort = "isort . --check"
check = { sequence = ["_check_black", "_check_isort", "lint"], help = "Check all potential format and linting issues.", ignore_fail = false }
test = { cmd = "pytest --cov=eargait --cov-report=term-missing --cov-report=xml", help = "Run Pytest with coverage." }
docs = { "script" = "_tasks:task_docs()",  help = "Build the html docs using Sphinx." }
bump_version = { "script" = "_tasks:task_update_version()" }

[tool.pyright]
pythonVersion = "3.8"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"